import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {schnorr} from '@noble/curves/secp256k1.js';
import * as c from './computeJobV1.ts';import * as r from './computeResultV1.ts';import {snapshot,job,key,input,hex,unhex} from '../tests/support/computeResultVectorsV1.ts';
const v=JSON.parse(readFileSync(new URL('../../../fixtures/compute_result_v1/result_vectors_v1.json',import.meta.url),'utf8'));
const raw=(x:any)=>unhex(x.bytes_hex),sig=(x:any,i=0)=>unhex(x.signatures[i].signature_hex);
const codecs={assignment:[r.decodeComputeAssignmentV1,r.encodeComputeAssignmentV1,(a:any,role:string)=>role==='worker'?r.computeAssignmentWorkerDigestV1(a):r.computeAssignmentCoordinatorDigestV1(a)],receipt:[r.decodeComputeReceiptV1,r.encodeComputeReceiptV1,r.computeReceiptSigningDigestV1],result:[r.decodeVerifiedComputeResultV1,r.encodeVerifiedComputeResultV1,r.computeResultSigningDigestV1],accounting:[r.decodeComputeResourceAccountingV1,r.encodeComputeResourceAccountingV1,r.computeResourceAccountingCommitmentV1],cancel:[r.decodeComputeCancelV1,r.encodeComputeCancelV1,r.computeCancelSigningDigestV1]} as const;
test('independent TS reproduces every frozen Rust byte, signature, commitment and mutation classification',()=>{assert.deepEqual(snapshot(),v);assert.deepEqual([r.COMPUTE_ASSIGNMENT_V1_BYTE_LEN,r.COMPUTE_RECEIPT_V1_BYTE_LEN,r.COMPUTE_RESULT_V1_BYTE_LEN,r.COMPUTE_CANCEL_V1_BYTE_LEN,r.COMPUTE_RESOURCE_ACCOUNTING_V1_BYTE_LEN],[91,152,56,55,25]);});
test('complete resolved lineage and signatures bind output and exact existing miner expansion',()=>{const j=job();c.verifyComputeRequestV1(j,unhex(v.request_signature_hex));for(const x of v.cases){const a=r.decodeComputeAssignmentV1(raw(x.assignment)),receipt=r.decodeComputeReceiptV1(raw(x.receipt)),counts=r.decodeComputeResourceAccountingV1(raw(x.accounting)),result=r.decodeVerifiedComputeResultV1(raw(x.result));r.verifyComputeAssignmentWorkerV1(a,sig(x.assignment));r.verifyComputeAssignmentCoordinatorV1(a,j,sig(x.assignment,1));r.verifyComputeReceiptSignatureV1(receipt,a,sig(x.receipt));r.verifyComputeReceiptContentV1(receipt,j,counts,input(),unhex(x.output_hex),unhex(x.evidence_hex));r.verifyComputeResultSignatureV1(result,j,a,receipt,sig(x.result));assert.equal(hex(r.computeResultCommitmentV1(result)),x.result.commitment_hex);assert.equal(hex(c.computeMinerSideV1(r.computeResultCommitmentV1(result),0)),x.miner_side_a_hex);assert.equal(hex(c.computeMinerSideV1(r.computeResultCommitmentV1(result),1)),x.miner_side_b_hex);
assert.throws(()=>r.verifyComputeResultLineageV1(result,{...j,programCommitment:new Uint8Array(32)},a,receipt));assert.throws(()=>r.verifyComputeReceiptSignatureV1(receipt,{...a,workerKey:schnorr.getPublicKey(key(9))},sig(x.receipt)));assert.throws(()=>r.verifyComputeResultLineageV1(result,j,a,{...receipt,outputCommitment:new Uint8Array(32)}));for(const f of [()=>r.signComputeAssignmentWorkerV1(a,key(9)),()=>r.signComputeAssignmentCoordinatorV1(a,j,key(9)),()=>r.signComputeReceiptV1(receipt,a,key(9)),()=>r.signComputeResultV1(result,j,a,receipt,key(9))])assert.throws(f);}
r.verifyComputeCancelSignatureV1(r.decodeComputeCancelV1(raw(v.cancel)),j,sig(v.cancel));});
test('every byte and signature mutation, truncation and trailing encoding is rejected or bound',()=>{for(const x of [...v.cases,{cancel:v.cancel}])for(const [name,codec] of Object.entries(codecs)){if(!x[name])continue;const [decode,encode,digest]=codec as any;const b=raw(x[name]);for(let i=0;i<b.length;i++)assert.throws(()=>decode(b.subarray(0,i)));for(const n of [1,32,200])assert.throws(()=>decode(Buffer.concat([b,Buffer.alloc(n)])));
for(let i=0;i<b.length;i++){const m=Uint8Array.from(b);m[i]^=1;let value;try{value=decode(m);}catch{}assert.equal(value!==undefined,x[name].single_bit_mutation_decodes[i]==='1',`${name} ${i}`);if(value){assert.equal(hex(encode(value)),hex(m));for(const s of x[name].signatures)assert.equal(schnorr.verify(unhex(s.signature_hex),digest(value,s.role),unhex(s.key_hex)),false);}}
const value=decode(b);for(const s of x[name].signatures)for(let i=0;i<64;i++){const bad=unhex(s.signature_hex);bad[i]^=1;assert.equal(schnorr.verify(bad,digest(value,s.role),unhex(s.key_hex)),false);}}});
test('roles are noninterchangeable with identical keys; signature randomness cannot alter result identity',()=>{const x=v.cases[0],a=r.decodeComputeAssignmentV1(raw(x.assignment)),receipt=r.decodeComputeReceiptV1(raw(x.receipt)),result=r.decodeVerifiedComputeResultV1(raw(x.result));const checks=[(s:Uint8Array)=>r.verifyComputeAssignmentWorkerV1(a,s),(s:Uint8Array)=>r.verifyComputeAssignmentCoordinatorV1(a,job(),s),(s:Uint8Array)=>r.verifyComputeReceiptSignatureV1(receipt,a,s),(s:Uint8Array)=>r.verifyComputeResultSignatureV1(result,job(),a,receipt,s)];const signatures=[sig(x.assignment),sig(x.assignment,1),sig(x.receipt),sig(x.result)];for(let i=0;i<4;i++)for(let k=0;k<4;k++){if(i===k)checks[i](signatures[k]);else assert.throws(()=>checks[i](signatures[k]));}
const alternate=schnorr.sign(r.computeResultSigningDigestV1(result),key(1),new Uint8Array(32).fill(2));assert.notEqual(hex(alternate),hex(signatures[3]));checks[3](alternate);assert.equal(hex(r.computeResultCommitmentV1(result)),x.result.commitment_hex);for(const f of checks)for(const n of [0,32,63,65])assert.throws(()=>f(new Uint8Array(n)));});
test('strict TS objects exclude aliases, optional fields, coercions and telemetry',()=>{const x=v.cases[1];for(const [name,codec] of Object.entries(codecs)){const [decode,encode]=codec as any;const value=decode(raw(name==='cancel'?v.cancel:x[name]));for(const k of Object.keys(value)){const missing={...value};delete missing[k];assert.throws(()=>encode(missing));const accessor={...value};let reads=0;Object.defineProperty(accessor,k,{get(){reads++;return value[k];},enumerable:true});assert.throws(()=>encode(accessor));assert.equal(reads,0);}
for(const metadata of ['telemetry','temperature','duration','backend','receivedAt','extra'])assert.throws(()=>encode({...value,[metadata]:0}));for(const version of [0,2,-0,'1',null,undefined])assert.throws(()=>encode({...value,version}));for(const k of Object.keys(value)){if(value[k] instanceof Uint8Array)for(const b of [[],null,'00',new Uint8Array(31),new Uint8Array(33)])assert.throws(()=>encode({...value,[k]:b}));if(typeof value[k]==='bigint')for(const n of [1,'1',null,-1n,1n<<64n])assert.throws(()=>encode({...value,[k]:n}));}}
for(let tag=0;tag<256;tag++){if(tag===1)continue;const b=raw(x.result);b[55]=tag;assert.throws(()=>r.decodeVerifiedComputeResultV1(b));}const a=r.decodeComputeAssignmentV1(raw(x.assignment));assert.throws(()=>r.encodeComputeAssignmentV1({...a,workerKey:new Uint8Array(32).fill(255)}));});
test('resource counts are exact, content-derived and do not set compensation',()=>{const x=v.cases[1],receipt=r.decodeComputeReceiptV1(raw(x.receipt)),a=r.decodeComputeResourceAccountingV1(raw(x.accounting));for(const name of ['inputBytes','outputBytes','evidenceBytes'] as const)assert.throws(()=>r.verifyComputeReceiptContentV1(receipt,job(),{...a,[name]:a[name]+1n},input(),unhex(x.output_hex),unhex(x.evidence_hex)));for(const x of v.accounting_extremes){const a=r.decodeComputeResourceAccountingV1(raw(x));assert.equal(a.inputBytes.toString(),x.input_bytes);assert.equal(a.outputBytes.toString(),x.output_bytes);assert.equal(a.evidenceBytes.toString(),x.evidence_bytes);assert.equal(hex(r.computeResourceAccountingCommitmentV1(a)),x.commitment_hex);}assert.equal(job().compensationSatoshis,10000n);});
